### ISSUE TITLE
Crash on open combat deck

### ISSUE THREAD

**Issue by hiop** [Nightdawg/Hurricane#8]
```
Exception in thread "Haven UI thread" java.lang.NullPointerException: Cannot invoke "haven.Widget$Event.propagate(haven.Widget)" because the return value of "java.lang.ThreadLocal.get()" is null
        at haven.Widget.mousemove(Widget.java:1332)
        at haven.FightWnd$BView.mousemove(FightWnd.java:557)
        at haven.Widget$MouseMoveEvent.shandle(Widget.java:1041)
        at haven.Widget.handle(Widget.java:873)
        at haven.Widget$Event.dispatch(Widget.java:826)
        at haven.Widget$MouseMoveEvent.propagation(Widget.java:1033)
        at haven.Widget$Event.propagate(Widget.java:816)
        at haven.Widget$Event.dispatch(Widget.java:828)
        at haven.Widget$MouseMoveEvent.propagation(Widget.java:1033)
        at haven.Widget$Event.propagate(Widget.java:816)
        at haven.Widget$Event.dispatch(Widget.java:828)
        at haven.Widget$MouseMoveEvent.propagation(Widget.java:1033)
        at haven.Widget$Event.propagate(Widget.java:816)
        at haven.Window.handle(Window.java:483)
        at haven.Widget$Event.dispatch(Widget.java:826)
        at haven.Widget$MouseMoveEvent.propagation(Widget.java:1033)
        at haven.Widget$Event.propagate(Widget.java:816)
        at haven.Widget$Event.dispatch(Widget.java:828)
        at haven.Widget$MouseMoveEvent.propagation(Widget.java:1033)
        at haven.Widget$Event.propagate(Widget.java:816)
        at haven.Widget$Event.dispatch(Widget.java:828)
        at haven.UI.dispatch(UI.java:617)
        at haven.UI.mousemove(UI.java:865)
        at haven.UIPanel$Dispatcher.dispatch(UIPanel.java:72)
        at haven.GLPanel$Loop.run(GLPanel.java:361)
        at haven.JOGLPanel.run(JOGLPanel.java:246)
        at java.base/java.lang.Thread.run(Thread.java:832)
        ```

**Comment by Nightdawg** [comment]
Yep, cursed post-merge issues, still working on them.
Fixed this too, will push commit soon, thanks
