### ISSUE TITLE
when rabbit flay

### ISSUE THREAD

**Issue by hiop** [Nightdawg/Hurricane#9]
```
Exception in thread "Haven UI thread" #<Resource gfx/invobjs/rabbit-carcass>
        at haven.Resource$Pool$Queued.get(Resource.java:552)
        at haven.Resource$Pool$Queued.get(Resource.java:523)
        at haven.Session$CachedRes$Ref.get(Session.java:126)
        at haven.Session$CachedRes$Ref.get(Session.java:117)
        at haven.Inventory.wdgmsg(Inventory.java:261)
        at haven.Widget.wdgmsg(Widget.java:739)
        at haven.Widget.wdgmsg(Widget.java:732)
        at haven.WItem.mousehover(WItem.java:369)
        at haven.Widget$MouseHoverEvent.shandle(Widget.java:1106)
        at haven.Widget.handle(Widget.java:877)
        at haven.Widget$Event.dispatch(Widget.java:830)
        at haven.Widget$MouseHoverEvent.propagation(Widget.java:1095)
        at haven.Widget$Event.propagate(Widget.java:820)
        at haven.Widget$Event.dispatch(Widget.java:832)
        at haven.Widget$MouseHoverEvent.propagation(Widget.java:1095)
        at haven.Widget$Event.propagate(Widget.java:820)
        at haven.Window.handle(Window.java:483)
        at haven.Widget$Event.dispatch(Widget.java:830)
        at haven.Widget$MouseHoverEvent.propagation(Widget.java:1095)
        at haven.Widget$Event.propagate(Widget.java:820)
        at haven.Widget$Event.dispatch(Widget.java:832)
        at haven.Widget$MouseHoverEvent.propagation(Widget.java:1095)
        at haven.Widget$Event.propagate(Widget.java:820)
        at haven.Widget$Event.dispatch(Widget.java:832)
        at haven.UI.dispatch(UI.java:617)
        at haven.UI.mousehover(UI.java:869)
        at haven.GLPanel$Loop.run(GLPanel.java:362)
        at haven.JOGLPanel.run(JOGLPanel.java:246)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by hiop** [comment]
However, next time there was no error.

**Comment by Nightdawg** [comment]
This looks like some cached resource error. Have you cleared your appdata folder before the world wipe?
IF you decide to clear your appdata now, remember to export your map file first
